"""initial_schema

Revision ID: bc2ad3ba5757
Revises: 
Create Date: 2026-07-29 21:57:21.203723
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'bc2ad3ba5757'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scans_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_patient_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('scan_id', sa.VARCHAR(), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), nullable=False),
    sa.Column('patient_name', sa.VARCHAR(), nullable=True),
    sa.Column('patient_dob', sa.VARCHAR(), nullable=True),
    sa.Column('patient_gender', sa.VARCHAR(), nullable=True),
    sa.Column('patient_eye', sa.VARCHAR(), nullable=True),
    sa.Column('patient_physician', sa.VARCHAR(), nullable=True),
    sa.Column('patient_notes', sa.TEXT(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('progress', sa.INTEGER(), nullable=True),
    sa.Column('primary_diagnosis', sa.VARCHAR(), nullable=True),
    sa.Column('diagnosis_detail', sa.VARCHAR(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('risk_score', sa.FLOAT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('icd10', sa.VARCHAR(), nullable=True),
    sa.Column('etdrs_grade', sa.VARCHAR(), nullable=True),
    sa.Column('probabilities', sqlite.JSON(), nullable=True),
    sa.Column('findings', sqlite.JSON(), nullable=True),
    sa.Column('recommendations', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=1)
    op.create_index(op.f('ix_scans_patient_id'), 'scans', ['patient_id'], unique=False)
    op.create_index(op.f('ix_scans_id'), 'scans', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('institution', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('specialty', sa.VARCHAR(), nullable=True),
    sa.Column('dark_mode', sa.BOOLEAN(), nullable=True),
    sa.Column('critical_alerts', sa.BOOLEAN(), nullable=True),
    sa.Column('report_ready', sa.BOOLEAN(), nullable=True),
    sa.Column('weekly_digest', sa.BOOLEAN(), nullable=True),
    sa.Column('model_updates', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('time_label', sa.VARCHAR(), nullable=True),
    sa.Column('action', sa.VARCHAR(), nullable=True),
    sa.Column('patient', sa.VARCHAR(), nullable=True),
    sa.Column('result', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('last_scan', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('risk', sa.VARCHAR(), nullable=True),
    sa.Column('contact', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=1)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    # ### end Alembic commands ###
